# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  # - repo: https://github.com/myint/autoflake
  #   rev: v2.0.0
  #   hooks:
  #     - id: autoflake
  #       args:
  #         [
  #           --in-place,
  #           --remove-all-unused-imports,
  #           --remove-unused-variable,
  #           --ignore-init-module-imports,
  #         ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v0.991
  #     hooks:
  #     -   id: mypy
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.12.1
  #   hooks:
  #   - id: blacken-docs

  # - repo: local
  #   hooks:
  # - id: isort
  #   name: isort
  #   stages: [commit]
  #   language: system
  #   entry: poetry run isort
  #   types: [python]

  # - id: black
  #   name: black
  #   stages: [commit]
  #   language: system
  #   entry: poetry run black
  #   types: [python]

  # - id: flake8
  #   name: flake8
  #   stages: [commit]
  #   language: system
  #   entry: poetry run flake8
  #   types: [python]

  # - id: mypy
  #   name: mypy
  #   stages: [commit]
  #   language: system
  #   entry: poetry run mypy .
  #   types: [python]
  #   pass_filenames: false

  # - id: pytest
  #   name: pytest
  #   stages: [commit]
  #   language: system
  #   entry: poetry run pytest -v
  #   types: [python]
  #   pass_filenames: false
  #   always_run: true

  # - id: pytest-cov
  #   name: pytest-cov
  #   stages: [push]
  #   language: system
  #   entry: poetry run pytest -v --cov --cov-fail-under=0
  #   types: [python]
  #   pass_filenames: false
  #   always_run: true