name: IP Check

on:
  workflow_dispatch:
  schedule:
    - cron: "10,20,30,40,50 * * * *"

jobs:
  check_ip:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check IP
        run: |
          python main.py --validate

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update IP Check
          branch: main
          push_options: '--force'

      - name: Delete Old Workflow Runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          workflow: ".github/workflows/ip_check.yml"
          older-than-seconds: 600  # Delete runs older than 10 minutes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
