name: Proxy Scraping

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  scrape_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Scrape Proxies
        run: |
          python main.py --scrape

      - name: Update Deployment Time
        run: |
          echo "Last proxy scrape time: $(date +'%Y-%m-%d %H:%M:%S %Z')" > README.md

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update Proxy Scraping
          branch: main
          push_options: '--force'
